import { 
  faClipboardList,
  faChartLine,
  faRobot, 
  faCheckCircle,
  faWrench,
  faBan,
  faMagnifyingGlass,
  faFilterCircleXmark,
  faChartColumn,
  faFileExcel,
  faArrowsUpDown,
  faEye,
  faFolderOpen,
  faMoon,
  faSun,
  faSort,
  faCircleInfo,
  faArrowUpRightFromSquare,
  faQuestionCircle,
  faLink,
  faTimesCircle,
  faCheck,
  faExclamation
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  faClipboardList,
  faChartLine,
  faRobot,
  faCheckCircle,
  faWrench,
  faBan,
  faMagnifyingGlass,
  faFilterCircleXmark,
  faChartLine,
  faChartColumn,
  faFileExcel,
  faArrowsUpDown,
  faEye,
  faFolderOpen,
  faMoon,
  faSun,
  faSort,
  faCircleInfo,
  faArrowUpRightFromSquare,
  faQuestionCircle,
  faLink,
  faTimesCircle,
  faCheck,
  faExclamation
};

export default ICONS;